package com.cupflow.pos.shared.logging;

public enum SecurityEventType {
    AUTHENTICATION_SUCCEEDED,
    AUTHENTICATION_FAILED,
    AUTHENTICATION_RATE_LIMITED,
    SESSION_EXPIRED,
    SESSION_INVALIDATED,
    ACCOUNT_SESSION_INVALIDATED,
    LOGOUT_SUCCEEDED,
    AUTHORIZATION_DENIED,
    CSRF_REJECTED
}
